#!/usr/bin/env bash
# subdomains configuration
domain_info(){
    dig "$2.$1" | grep -A1 "ANSWER SECTION:" | grep "$2" | awk -v subdomain="$2" '{print "The subdomain " subdomain " is a " $4 " record and points to " $5}'
}

if [ "$#" = 1 ]
then
    for index in "www" "lb-01" "web-01" "web-02"; do
		domain_info "$1" "$index"
	done
elif [ "$#" = 2 ]
then
    domain_info "$1" "$2"
fi
