#!/usr/bin/env bash
#This script that displays catch diferent bash signals and displays a messegge with it
# shellcheck disable=SC2002
# shellcheck disable=SC2034
echo $$ > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"; rm -rf /var/run/holbertonscript.pid; exit(0)' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -rf /var/run/holbertonscript.pid; exit(0)' SIGQUIT

while :
do
    echo "To infinity and beyond"
    sleep 2
done
