#!/usr/bin/env bash
# displays the content of the file /etc/passwd with an specific format
while IFS= read -r line
do
    user=$(echo "$line" | cut -f 1 -d ':')
    group_ID=$(echo "$line" | cut -f 4 -d ':')
    home_dir=$(echo "$line" | cut -f 6 -d ':')
    _command=$(echo "$line" | cut -f 7 -d ':')
    user_ID=$(echo "$line" | cut -f 3 -d ':')
    password=$(echo "$line" | cut -f 2 -d ':')
    user_INFO=$(echo "$line" | cut -f 5 -d ':')


    echo -n "The user $user is part of the $group_ID gang, "
    echo -n "lives in $home_dir and rides $_command."
    echo -n " $user_ID's place is protected by the passcode $password, "
    echo "more info about the user here: $user_INFO"
done < "/etc/passwd"
