#!/usr/bin/env bash                                                             
# This script prints the info of apache-access.log file in the format: IP HTTP_CODE
awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -nr
