#!/usr/bin/env bash
# This script resolves to 127.0.0.2 the localhost and to 8.8.8.8 the facebook.com
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
