#!/usr/bin/env bash
# This script resolves to 127.0.0.2 the localhost and to 8.8.8.8 the facebook.com
#sed -i 's/8.8.8.8/157.240.11.35/' ~/hosts.new
#sed -i 's/127.0.0.2/127.0.0.1/' ~/hosts.new
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i 'a\8.8.8.8 facebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
